// src/pages/index.vue
<template>
  <main class="main w-full h-full rounded flex items-center justify-center">
    <div
      class="rounded flex flex-wrap items-center justify-center flex-col sm:flex-row py-16 sm:py-8 mx-2 my-2 sm:px-16"
    >
      <Icon />
      <Profile />
    </div>
  </main>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({})
</script>

<style lang="scss" scoped>
.main {
  div {
    background: #fcfcf3;
  }
}
</style>

// src/pages/index.tsx
import React from 'react'
import Icon from '../components/profile/ProfileIcon'
import Contents from '../components/profile/ProfileContents'

const ProfileIcon = () => {
  return (
    <div>
      <Icon />
    </div>
  )
}

const ProfileContents = () => {
  return (
    <div>
      <Contents />
    </div>
  )
}

const Profile = () => {
  return (
    <div className="flex flex-wrap items-center justify-center flex-col sm:flex-row">
      <ProfileIcon />
      <ProfileContents />
    </div>
  )
}

export default Profile
